// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xrpbjtdbwuodfixgpapx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhycGJqdGRid3VvZGZpeGdwYXB4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcyNTMwMjUsImV4cCI6MjA2MjgyOTAyNX0.MQvIzfrm1qNCmLAxX8bIxaPMXl_7v6JHrRS6Wr1QpY8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);